### PR TITLE
update compilation documentation for macOS

### PR DESCRIPTION
**Pull request by evanbowman**
Let me know if you want me to format anything differently, I'd be happy to make changes!

Edit: view the resulting README here: https://github.com/evanbowman/NanoBoyAdvance/blob/20240124-ebowman-update-macOS-compilation-docs/docs/COMPILING.md#2-setup-cmake-build-directory

### CODE REVIEW

**Comment by fleroviux** [comment]
I don't think this is related to the macOS version. I probably simply forgot adding this to the docs when the Qt frontend was merged. Maybe instead of the NOTE you could split `2. Setup CMake build directory` into two subsections for `Linux and FreeBSD` and `macOS`, similar to above? Thanks a lot.

**Comment by evanbowman** [comment]
Good suggestion! At first I didn't realize that this section was just for unix, and I didn't want to have to split the setup instructions into one per each OS, but if there're only two sections, for macOS and linux/bsd, then I think it makes the most sense to split it. Will push updates soon.

**Comment by evanbowman** [comment]
I have currently duplicated `NOTE: the location and name of the build directory is arbitrary.` Into each section for the sake of clarity. I could also move it to the top of section 2.

**Comment by fleroviux** [comment]
Thanks, LGTM!

**Pull request merged**
